//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Визит.
    /// </summary>
    // *** Start programmer edit section *** (Визит CustomAttributes)

    // *** End programmer edit section *** (Визит CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВизитE", new string[] {
            "КодDизита as \'Код dизита\'",
            "НачалоСеанса as \'Начало сеанса\'",
            "КонецСеанса as \'Конец сеанса\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Клиент.ФИО"})]
    [AssociatedDetailViewAttribute("ВизитE", "ЗаписьВизита", "ЗаписьВизитаE", true, "", "Табличная часть состав визита", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ВизитE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ВизитL", new string[] {
            "КодDизита as \'Код dизита\'",
            "НачалоСеанса as \'Начало сеанса\'",
            "КонецСеанса as \'Конец сеанса\'",
            "Клиент.ФИО as \'ФИО\'"})]
    public class Визит : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодDизита;
        
        private int fНачалоСеанса;
        
        private int fКонецСеанса;
        
        private IIS.Bekap_3.Клиент fКлиент;
        
        private IIS.Bekap_3.DetailArrayOfЗаписьВизита fЗаписьВизита;
        
        // *** Start programmer edit section *** (Визит CustomMembers)

        // *** End programmer edit section *** (Визит CustomMembers)

        
        /// <summary>
        /// КодDизита.
        /// </summary>
        // *** Start programmer edit section *** (Визит.КодDизита CustomAttributes)

        // *** End programmer edit section *** (Визит.КодDизита CustomAttributes)
        public virtual int КодDизита
        {
            get
            {
                // *** Start programmer edit section *** (Визит.КодDизита Get start)

                // *** End programmer edit section *** (Визит.КодDизита Get start)
                int result = this.fКодDизита;
                // *** Start programmer edit section *** (Визит.КодDизита Get end)

                // *** End programmer edit section *** (Визит.КодDизита Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.КодDизита Set start)

                // *** End programmer edit section *** (Визит.КодDизита Set start)
                this.fКодDизита = value;
                // *** Start programmer edit section *** (Визит.КодDизита Set end)

                // *** End programmer edit section *** (Визит.КодDизита Set end)
            }
        }
        
        /// <summary>
        /// КонецСеанса.
        /// </summary>
        // *** Start programmer edit section *** (Визит.КонецСеанса CustomAttributes)

        // *** End programmer edit section *** (Визит.КонецСеанса CustomAttributes)
        public virtual int КонецСеанса
        {
            get
            {
                // *** Start programmer edit section *** (Визит.КонецСеанса Get start)

                // *** End programmer edit section *** (Визит.КонецСеанса Get start)
                int result = this.fКонецСеанса;
                // *** Start programmer edit section *** (Визит.КонецСеанса Get end)

                // *** End programmer edit section *** (Визит.КонецСеанса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.КонецСеанса Set start)

                // *** End programmer edit section *** (Визит.КонецСеанса Set start)
                this.fКонецСеанса = value;
                // *** Start programmer edit section *** (Визит.КонецСеанса Set end)

                // *** End programmer edit section *** (Визит.КонецСеанса Set end)
            }
        }
        
        /// <summary>
        /// НачалоСеанса.
        /// </summary>
        // *** Start programmer edit section *** (Визит.НачалоСеанса CustomAttributes)

        // *** End programmer edit section *** (Визит.НачалоСеанса CustomAttributes)
        public virtual int НачалоСеанса
        {
            get
            {
                // *** Start programmer edit section *** (Визит.НачалоСеанса Get start)

                // *** End programmer edit section *** (Визит.НачалоСеанса Get start)
                int result = this.fНачалоСеанса;
                // *** Start programmer edit section *** (Визит.НачалоСеанса Get end)

                // *** End programmer edit section *** (Визит.НачалоСеанса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.НачалоСеанса Set start)

                // *** End programmer edit section *** (Визит.НачалоСеанса Set start)
                this.fНачалоСеанса = value;
                // *** Start programmer edit section *** (Визит.НачалоСеанса Set end)

                // *** End programmer edit section *** (Визит.НачалоСеанса Set end)
            }
        }
        
        /// <summary>
        /// Визит.
        /// </summary>
        // *** Start programmer edit section *** (Визит.Клиент CustomAttributes)

        // *** End programmer edit section *** (Визит.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Bekap_3.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Визит.Клиент Get start)

                // *** End programmer edit section *** (Визит.Клиент Get start)
                IIS.Bekap_3.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Визит.Клиент Get end)

                // *** End programmer edit section *** (Визит.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.Клиент Set start)

                // *** End programmer edit section *** (Визит.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Визит.Клиент Set end)

                // *** End programmer edit section *** (Визит.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Визит.
        /// </summary>
        // *** Start programmer edit section *** (Визит.ЗаписьВизита CustomAttributes)

        // *** End programmer edit section *** (Визит.ЗаписьВизита CustomAttributes)
        public virtual IIS.Bekap_3.DetailArrayOfЗаписьВизита ЗаписьВизита
        {
            get
            {
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Get start)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Get start)
                if ((this.fЗаписьВизита == null))
                {
                    this.fЗаписьВизита = new IIS.Bekap_3.DetailArrayOfЗаписьВизита(this);
                }
                IIS.Bekap_3.DetailArrayOfЗаписьВизита result = this.fЗаписьВизита;
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Get end)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Set start)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Set start)
                this.fЗаписьВизита = value;
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Set end)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВизитE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВизитE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВизитE", typeof(IIS.Bekap_3.Визит));
                }
            }
            
            /// <summary>
            /// "ВизитL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВизитL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВизитL", typeof(IIS.Bekap_3.Визит));
                }
            }
        }
    }
}
