//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав услуги.
    /// </summary>
    // *** Start programmer edit section *** (СоставУслуги CustomAttributes)

    // *** End programmer edit section *** (СоставУслуги CustomAttributes)
    [AutoAltered()]
    [Caption("Состав услуги")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставУслугиE", new string[] {
            "Количество as \'Количество\'",
            "Товар as \'Товар\'",
            "Товар.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Товар.Наименование"})]
    [MasterViewDefineAttribute("СоставУслугиE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СоставУслуги : ICSSoft.STORMNET.DataObject
    {
        
        private double fКоличество;
        
        private IIS.Bekap_3.Товар fТовар;
        
        private IIS.Bekap_3.Услуга fУслуга;
        
        // *** Start programmer edit section *** (СоставУслуги CustomMembers)

        // *** End programmer edit section *** (СоставУслуги CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.Количество CustomAttributes)
        public virtual double Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.Количество Get start)

                // *** End programmer edit section *** (СоставУслуги.Количество Get start)
                double result = this.fКоличество;
                // *** Start programmer edit section *** (СоставУслуги.Количество Get end)

                // *** End programmer edit section *** (СоставУслуги.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.Количество Set start)

                // *** End programmer edit section *** (СоставУслуги.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставУслуги.Количество Set end)

                // *** End programmer edit section *** (СоставУслуги.Количество Set end)
            }
        }
        
        /// <summary>
        /// Состав услуги.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.Товар CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Bekap_3.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.Товар Get start)

                // *** End programmer edit section *** (СоставУслуги.Товар Get start)
                IIS.Bekap_3.Товар result = this.fТовар;
                // *** Start programmer edit section *** (СоставУслуги.Товар Get end)

                // *** End programmer edit section *** (СоставУслуги.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.Товар Set start)

                // *** End programmer edit section *** (СоставУслуги.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (СоставУслуги.Товар Set end)

                // *** End programmer edit section *** (СоставУслуги.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Bekap_3.Услуга.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.Услуга CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.Услуга CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Услуга"})]
        public virtual IIS.Bekap_3.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.Услуга Get start)

                // *** End programmer edit section *** (СоставУслуги.Услуга Get start)
                IIS.Bekap_3.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (СоставУслуги.Услуга Get end)

                // *** End programmer edit section *** (СоставУслуги.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.Услуга Set start)

                // *** End programmer edit section *** (СоставУслуги.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (СоставУслуги.Услуга Set end)

                // *** End programmer edit section *** (СоставУслуги.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставУслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставУслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставУслугиE", typeof(IIS.Bekap_3.СоставУслуги));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставУслуги.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставУслуги CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставУслуги CustomAttributes)
    public class DetailArrayOfСоставУслуги : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Bekap_3.DetailArrayOfСоставУслуги members)

        // *** End programmer edit section *** (IIS.Bekap_3.DetailArrayOfСоставУслуги members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставУслуги by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставУслуги.
        /// </summary>
        public DetailArrayOfСоставУслуги(IIS.Bekap_3.Услуга fУслуга) : 
                base(typeof(СоставУслуги), ((ICSSoft.STORMNET.DataObject)(fУслуга)))
        {
        }
        
        public IIS.Bekap_3.СоставУслуги this[int index]
        {
            get
            {
                return ((IIS.Bekap_3.СоставУслуги)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Bekap_3.СоставУслуги dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
