//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуга.
    /// </summary>
    // *** Start programmer edit section *** (Услуга CustomAttributes)

    // *** End programmer edit section *** (Услуга CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УслугаE", new string[] {
            "услуги as \'Услуги\'",
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'",
            "Длительность as \'Длительность\'"})]
    [AssociatedDetailViewAttribute("УслугаE", "СоставУслуги", "СоставУслугиE", true, "", "Табличная часть состав услуги", true, new string[] {
            ""})]
    [View("УслугаL", new string[] {
            "услуги as \'Услуги\'",
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'",
            "Длительность as \'Длительность\'"})]
    public class Услуга : ICSSoft.STORMNET.DataObject
    {
        
        private int fуслуги;
        
        private string fНаименование;
        
        private double fЦена;
        
        private int fДлительность;
        
        private IIS.Bekap_3.DetailArrayOfСоставУслуги fСоставУслуги;
        
        // *** Start programmer edit section *** (Услуга CustomMembers)

        // *** End programmer edit section *** (Услуга CustomMembers)

        
        /// <summary>
        /// Длительность.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.Длительность CustomAttributes)

        // *** End programmer edit section *** (Услуга.Длительность CustomAttributes)
        public virtual int Длительность
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.Длительность Get start)

                // *** End programmer edit section *** (Услуга.Длительность Get start)
                int result = this.fДлительность;
                // *** Start programmer edit section *** (Услуга.Длительность Get end)

                // *** End programmer edit section *** (Услуга.Длительность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.Длительность Set start)

                // *** End programmer edit section *** (Услуга.Длительность Set start)
                this.fДлительность = value;
                // *** Start programmer edit section *** (Услуга.Длительность Set end)

                // *** End programmer edit section *** (Услуга.Длительность Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.Наименование CustomAttributes)

        // *** End programmer edit section *** (Услуга.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.Наименование Get start)

                // *** End programmer edit section *** (Услуга.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Услуга.Наименование Get end)

                // *** End programmer edit section *** (Услуга.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.Наименование Set start)

                // *** End programmer edit section *** (Услуга.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Услуга.Наименование Set end)

                // *** End programmer edit section *** (Услуга.Наименование Set end)
            }
        }
        
        /// <summary>
        /// услуги.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.услуги CustomAttributes)

        // *** End programmer edit section *** (Услуга.услуги CustomAttributes)
        public virtual int услуги
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.услуги Get start)

                // *** End programmer edit section *** (Услуга.услуги Get start)
                int result = this.fуслуги;
                // *** Start programmer edit section *** (Услуга.услуги Get end)

                // *** End programmer edit section *** (Услуга.услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.услуги Set start)

                // *** End programmer edit section *** (Услуга.услуги Set start)
                this.fуслуги = value;
                // *** Start programmer edit section *** (Услуга.услуги Set end)

                // *** End programmer edit section *** (Услуга.услуги Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.Цена CustomAttributes)

        // *** End programmer edit section *** (Услуга.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.Цена Get start)

                // *** End programmer edit section *** (Услуга.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Услуга.Цена Get end)

                // *** End programmer edit section *** (Услуга.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.Цена Set start)

                // *** End programmer edit section *** (Услуга.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Услуга.Цена Set end)

                // *** End programmer edit section *** (Услуга.Цена Set end)
            }
        }
        
        /// <summary>
        /// Услуга.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.СоставУслуги CustomAttributes)

        // *** End programmer edit section *** (Услуга.СоставУслуги CustomAttributes)
        public virtual IIS.Bekap_3.DetailArrayOfСоставУслуги СоставУслуги
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.СоставУслуги Get start)

                // *** End programmer edit section *** (Услуга.СоставУслуги Get start)
                if ((this.fСоставУслуги == null))
                {
                    this.fСоставУслуги = new IIS.Bekap_3.DetailArrayOfСоставУслуги(this);
                }
                IIS.Bekap_3.DetailArrayOfСоставУслуги result = this.fСоставУслуги;
                // *** Start programmer edit section *** (Услуга.СоставУслуги Get end)

                // *** End programmer edit section *** (Услуга.СоставУслуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.СоставУслуги Set start)

                // *** End programmer edit section *** (Услуга.СоставУслуги Set start)
                this.fСоставУслуги = value;
                // *** Start programmer edit section *** (Услуга.СоставУслуги Set end)

                // *** End programmer edit section *** (Услуга.СоставУслуги Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УслугаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугаE", typeof(IIS.Bekap_3.Услуга));
                }
            }
            
            /// <summary>
            /// "УслугаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугаL", typeof(IIS.Bekap_3.Услуга));
                }
            }
        }
    }
}
